### PR TITLE
Add custom color picker

### LINKED ISSUE #5: Allow selecting any colour
Have you considered using the browser's native colour picker, to allow selection of any colour?

i.e. if enabled, an extra item could appear in the list of colours in the picker. When clicked it opens the native colour picker:

image

The icon on the extra item could explain it's for "any colour" by having a rainbow effect e.g.

image

If you don't like the idea of the native picker, it could even provide just a text box to provide a custom colour.

### PR DESCRIPTION
**Pull request by HaoCherHong**
fix #5

### CODE REVIEW

**Comment by flaming-cl** [comment]
Thanks for you contribution! Outstanding work!  

Just to make your great work better than perfect, here are some tips for your commit:  
image

The red dot in the above screenshot is the button for the customized color. 
Here are two things that we may need to discuss:
1. Should it be aligned with the predefined color buttons?
2. Do you mind to make it look different from the predefined color buttons by giving it another CSS styling?

Thanks!

**Comment by HaoCherHong** [comment]
> * Should it be aligned with the predefined color buttons?

Yes, I think we should do that, but also adding a splitter line between predefined colors and custom picker

> * Do you mind to make it look different from the predefined color buttons by giving it another CSS styling?

Sure, I'm thinking about what look should it be. Any suggestion?

**Comment by AlecRust** [comment]
One option is the "rainbow" colours shown in original issue.

**Comment by flaming-cl** [comment]
1. Do you mind to make it look different from the predefined color buttons by giving it another CSS styling?
> Sure, I'm thinking about what look should it be. Any suggestion?

Like [AlecRust](https://github.com/AlecRust) said, maybe a rainbow colors button. Or we can simplify it to a button with rainbow borders. I can add this soon.

---
2. Should it be aligned with the predefined color buttons?
> Yes, I think we should do that, but also adding a splitter line between predefined colors and custom picker

If we have given the custom picker button a different look, the custom picker now can be put together with predefined colors. 😊

**Pull request merged**
